name: Check Markdown files correctness

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # Extract links from Markdown texts and check if they are alive
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
